name: package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1
      
      - name: install devDependencies
      - run: npm install -D

      - name: switch directories to template project
      - run: cd ./test/smoke/template
      
      - name: install template project's dependencies
      - run: npm install -D