
name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
 
  test:
 
    runs-on: ubuntu-latest

   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      

          
          
      - name: setup node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "18.X"
          
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-

      - name: install dep
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install -D
        
      - name: switch to template project
        run: cd ./test/smoke/template
        
        
      - name: Cache node_modules
        id: cache-node-modules-template
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-
        
      - name: install template project dep
        if: steps.cache-node-modules-template.outputs.cache-hit != 'true'
        run: yarn install -D
        
      - name: run test scripts
        run: yarn run test
        
